GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Eat food"
}


### will pass back the thing we deleted

DELETE http://localhost:3001/todo/delete/63fb20068fcd54c9697b5490


###

PUT http://localhost:3001/todo/complete/63fbca398fcd54c9697b549c